/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'dirk' at '12/28/15 10:05 PM' with Gradle 2.5-rc-2
 *
 * @author dirk, @date 12/28/15 10:05 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
